name: Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build_and_test_arm64:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        gcc_version: [13]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v6

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: |
        sudo apt-get update 
        sudo apt-get -y install g++-${{matrix.gcc_version}}
        sudo apt-get install python3-numpy

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="g++-${{matrix.gcc_version}}" -DSIMD_TARGET="" -DSIMD_TEST_FLAGS="-march=native -march=armv9-a+sve+sve2+i8mm+bf16" -DSIMD_PERF=ON -DSIMD_SVE=ON -DSIMD_SVE2=ON -DSIMD_SHARED=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)
      
    - name: Test C++ All
      working-directory: ${{github.workspace}}/build
      run: |
        export LD_LIBRARY_PATH="${{github.workspace}}/build":$LD_LIBRARY_PATH
        ./Test "-r=.." -m=a -tt=4 -ts=5 -mt=10 -w=640 -h=480 -c=256
        
    - name: Test C++ Custom
      working-directory: ${{github.workspace}}/build
      run: |
        export LD_LIBRARY_PATH="${{github.workspace}}/build":$LD_LIBRARY_PATH
        ./Test "-r=.." -m=a -tt=1 -ts=5 -wu=0 -de=0 -fi=ToMemory
        
    - name: Test Python
      if: ${{ matrix.build_type == 'Release' }}
      working-directory: ${{github.workspace}}/build
      run: python3 ./Test.py "-r=.."
      
  build_and_test_mingw:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc git make
        pacboy: toolchain:p cmake:p ninja:p

    - name: Host properties
      shell: pwsh
      run: echo "$((Get-CimInstance Win32_Processor).Name), $((Get-CimInstance Win32_Processor).NumberOfCores) cores, $((Get-CimInstance Win32_Processor).NumberOfLogicalProcessors) threads."

    - name: Configure CMake
      run: cmake ./prj/cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TARGET="x86_64" -DSIMD_GET_VERSION=OFF -DSIMD_TEST_FLAGS="-march=native"

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} --parallel4

    - name: Test
      working-directory: build
      run: ./Test.exe "-r=.." -m=a -tt=4 -ot=log_${{matrix.build_type}}.txt -ts=5 -mt=1 -w=640 -h=480 -c=256


