name: Test

on:
  push:
    branches: [ "dev" ]

jobs:
  build_and_test_arm64:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        gcc_version: [13]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: |
        sudo apt-get update 
        sudo apt-get -y install g++-${{matrix.gcc_version}}
        sudo apt-get install python3-numpy

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="g++-${{matrix.gcc_version}}" -DSIMD_TARGET="" -DSIMD_TEST_FLAGS="-march=native -march=armv8-a+sve" -DSIMD_SVE=ON -DSIMD_SHARED=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)
      
    - name: Test C++
      working-directory: ${{github.workspace}}/build
      run: |
        export LD_LIBRARY_PATH="${{github.workspace}}/build":$LD_LIBRARY_PATH
        ./Test "-r=.." -m=a -tt=0 -ts=5 -mt=100 -w=640 -h=480 -c=256 -fi=AbsDifference -fe=Sum
        
    - name: Test Python
      working-directory: ${{github.workspace}}/build
      run: python3 ./Test.py "-r=.."
